### ISSUE TITLE
Clean up search interface

### ISSUE THREAD

**Issue by penelopeysm** [Urban-Analytics-Technology-Platform/popgetter-cli#49]
(1) SearchText::context should not be a vector as it should not be possible to be empty. (The CLI parser does not allow it to be empty anyway).

https://github.com/Urban-Analytics-Technology-Platform/popgetter-cli/blob/dac6fad62b7dc124bdce1607d805b3a4e5d23d75/src/search.rs#L148-L152

Classically the way to enforce non-emptiness is to replace a vector with a tuple of an element plus a vector. It seems that there is a crate for this: https://docs.rs/nonempty/latest/nonempty/

This means we can get rid of the `impl From<SearchText> for Option<Expr>` and just make it a `impl From<SearchText> for Expr`

https://github.com/Urban-Analytics-Technology-Platform/popgetter-cli/blob/dac6fad62b7dc124bdce1607d805b3a4e5d23d75/src/search.rs#L54-L73

(2) The remaining search fields should be converted into Vecs themselves instead of Options of Vecs

https://github.com/Urban-Analytics-Technology-Platform/popgetter-cli/blob/dac6fad62b7dc124bdce1607d805b3a4e5d23d75/src/search.rs#L189-L196

**Comment by sgreenbury** [comment]
Closing following #57 being merged.
