### ISSUE TITLE
Expect exact matches on -g/--geometry-level

### ISSUE THREAD

**Issue by andrewphilipsmith** [Urban-Analytics-Technology-Platform/popgetter-cli#80]
When specifying a geometry level (-g/--geometry-level), I would expect the default behaviour to only include expected matches. Failing that, I would like an option to require exact matches only.

# How to reproduce
```
popgetter metrics -c gb_eaw -g "oa" -t "Number of cars or vans"
```
# Expected Result

Only return results where `geometry=="oa"`

# Actual Result

Returns results where `str(geometry).contains("oa")`. (eg msoa, lsoa, oa)

**Comment by sgreenbury** [comment]
Closing as superseded by #81.
