### ISSUE TITLE
Python Bindings

### ISSUE THREAD

**Issue by stuartlynn** [Urban-Analytics-Technology-Platform/popgetter-cli#9]
Once library is stable, start adding pyo3 bindings and generate a python library.

- [ ] Write bindings 
- [ ] Create python module 
- [ ] Publish python module (CI)
- [ ] PyDocs

**Comment by sgreenbury** [comment]
Next steps including outstanding tasks following merging #84:
- [ ] Following a PR for #81, explore using the initial python API to identify improvements and requirements
- [ ] Write structs for python options to allow easier calling of the lib
- [ ] Add Python tests
- [ ] Write some convenience methods to get the resulting dataframes back as geopandas dataframes 
- [ ] Documentation using pydoc
- [ ] CI to publish to pypi and pydocs

**Comment by sgreenbury** [comment]
Closing this one with initial bindings merged in #84 and opened #87 for next steps.
